import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Human - SQL Translator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="
        flex flex-col bg-gray-900 items-center  mx-auto  min-h-screen py-4
      ">
        <h1 className="
          text-3xl font-bold text-white mt-8
        ">
          Human - SQL Translator
        </h1>
        <div className="
          flex flex-col  p-8 border-2 bg-gray-800 border-gray-700 mt-12 w-auto rounded-md 
        ">
          <div className="
          flex flex-row
            
          ">
            <h2 className="
            justify-start
              text-l font-bold text-white
            ">
              Human Language Query
            </h2>
          </div>
          <div className="
            flex text-center
          ">
            <textarea className="
               border-2 border-gray-700 bg-gray-700 rounded-md p-2 mt-4 text-white
            "
              rows={3}
              cols={40}
              required
              placeholder="e.g. show me all the cars that are red "

            ></textarea>
          </div>
          <div className="
            flex flex-row justify-start
          ">
            <button className="
              bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4
            ">
              Translate to SQL
            </button>
          </div>
          <div className="">
            
          </div>


        </div>
        
      </main>
    </>
  )
}
